{% set name = "validate_email" %}
{% set version = "1.3" %}
{% set sha256 = "784719dc5f780be319cdd185dc85dd93afebdb6ebb943811bc4c7c5f9c72aeaf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - validate_email

about:
  home: https://github.com/syrusakbary/validate_email
  license: LGPL
  license_family: GPL
  license_file: LICENSE
  summary: 'Validate_email is a package for Python that check if an email is
            valid, properly formatted and really exists.'

  dev_url: https://github.com/syrusakbary/validate_email

extra:
  recipe-maintainers:
    - nikicc
    - mariusvniekerk
    - xylar
